### ISSUE TITLE
Cannot "go get" this repository

### ISSUE THREAD

**Issue by cephalization** [deepgram-devs/deepgram-go-sdk#36]
## What is the current behavior?

When I run the following command from the root of my own project

```
go get -u github.com/deepgram-devs/deepgram-go-sdk
```

I receive the following error

```
go: downloading github.com/deepgram-devs/deepgram-go-sdk v0.6.1
go: github.com/deepgram-devs/deepgram-go-sdk@v0.6.1: parsing go.mod:
        module declares its path as: github.com/deepgram-devs/go-sdk
                but was required as: github.com/deepgram-devs/deepgram-go-sdk
```

## Steps to reproduce

Run the following command from the root of any other go.mod containing folder

```
go get -u github.com/deepgram-devs/deepgram-go-sdk
```

Like

```
mkdir test-go-get
cd test-go-get
go mod init com.example.test-go-get
go get -u github.com/deepgram-devs/deepgram-go-sdk
```

## Expected behavior

This sdk successfully installs in my project and I can subsequently import Public functions and structs via import anywhere else in my project

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** MacOS 13.2.1 (22D68)
- **Language:** Go
- **Browser:** N/A

## Other information

I'm not very experienced in the Go ecosystem but I think this can be fixed with a small tweak to the package name in go.mod in this repo

**Comment by SandraRodgers** [comment]
Hi @cephalization ,

I tested this and encountered the same error. This is because the current docs say:

Clone the repository:
```
git clone https://github.com/deepgram-devs/deepgram-go-sdk/
```
Move into the directory and install the dependencies:
```
cd deepgram-go-sdk

go get .
```

I believe there is a missing step. I think you need to move into the 'deepgram' directory, so do this instead:

```
cd deepgram-go-sdk

cd deepgram

go get
```

For me, I just needed to `go get`, not `go get .`

Could you test this and let me know if it works for you? I will update the readme to reflect this.
